### ISSUE TITLE
Transform hangs up and is killed

### ISSUE THREAD

**Issue by AlbertoOddness** [haruishi43/equilib#17]
Hi! I'm trying to run the code from the example you have, but when I get to the function call to transform an equirectangular image into a perspective, the process hangs up and is killed.

Currently using numpy 1.24.2, tried both with torch 1.13.1 and also torch 2.0.1, but with either I get the same problem. Running python 3.10.12.

Any ideas?

**Comment by haruishi43** [comment]
@AlbertoOddness thanks for reporting! Currently, the CI is passing with the latest 3.8, 3.9, and 3.10 and I haven't came across any hang ups before, but I'll take a look.

Can you tell me the OS and hardware. I'm pretty sure the hang up might be due to not enough vram or ram.

**Comment by AlbertoOddness** [comment]
> Also, try the transform with lower resolution to see if the code works or not.

This was the issue! That's embarrassing 😅 I was opening a raw equirectangular image which was way too large for my memory.

Thank you!
