### ISSUE TITLE
Inquiry about Input to cube2equi

### ISSUE THREAD

**Issue by TakieddineSOUALHI** [haruishi43/equilib#20]
Hi,

First of all, thank you so much for creating this tool. It's beneficial for me as a computer vision researcher. I have a question about passing a list of images, to get a panoramic image. What is the specific order of the cubemap images in the list before using the function `cube2qui`?

Thank you so much; keep up the amazing work!

**Comment by haruishi43** [comment]
@TakieddineSOUALHI I'm glad the library helps!

Sorry for the lack of documentation.
The cubemap's order is: "Front Right Back Left Up Down"
(See [cube2equi/numpy.py](https://github.com/haruishi43/equilib/blob/65ccb7cc649bf2568dedf4bb768ece4d1fdc8227/equilib/cube2equi/numpy.py#L123))
