### ISSUE TITLE
Error 'equi2pers module not found'

### ISSUE THREAD

**Issue by canjmp** [haruishi43/equilib#21]
Pylance identifies 'equi2pers' as a module. It is then used later in the code as a function. This is the cause for the error.

I have very limited knowledge of Python and coding in general. I think 'equi2pers' is identified as a module instead of a function is due to the source code is not interpreted as expected by Python 3.12 which I am running.

BACKGROUND
I attempted to run your example code you provided at: https://github.com/haruishi43/equilib

I first ran the example using ‘Equi2Pers’ and Pylance could not find ‘Equi2Pers’. I then attempted the second example using ‘equi2pers’. Pylance identified it as a module.

Here is what I was running which is identical to the example but for 'my_img.jpg' and the last to lines of code to print 'perspective_image.jpg':

#This is the example code for 'equilib'
import numpy as np
from PIL import Image
from equilib import equi2pers

# Input equirectangular image
equi_img = Image.open("./my_image.jpg")
equi_img = np.asarray(equi_img)
equi_img = np.transpose(equi_img, (2, 0, 1))

# rotations
rots = {
    'roll': 0.,
    'pitch': np.pi/4,  # rotate vertical
    'yaw': np.pi/4,  # rotate horizontal
}

# Run equi2pers
pers_img = equi2pers(
    equi=equi_img,
    rots=rots,
    height=480,
    width=640,
    fov_x=90.0,
    mode="bilinear",
)

pers_img = Image.fromarray(pers_img.transpose((1, 2, 0)))
pers_img.save("./perspective_image.jpg")

Here is the the message at the terminal:

  File "c:\Users\xxxx\Desktop\STUFF\Test Area 19 - Y P R python\E2Pr.py", line 19, in <module>
    pers_img = equi2pers(
               ^^^^^^^^^^
TypeError: 'module' object is not callable

**Comment by haruishi43** [comment]
@canjmp Thanks for testing and reporting a thorough walkthrough on getting equilib to work on Windows! It's great that you got the code to run.

Just a heads up, I'm importing every function in the __init__.py (https://github.com/haruishi43/equilib/blob/65ccb7cc649bf2568dedf4bb768ece4d1fdc8227/equilib/__init__.py#L9).
So I'm confused why python won't recognize `equi2pers` on your setup. I'll test this when I have the time.

**Comment by jsomeara** [comment]
I also got this issue

**Comment by haruishi43** [comment]
@jsomeara hi, are you using windows?

**Comment by jsomeara** [comment]
No. I originally got this error on Google colab.

**Comment by haruishi43** [comment]
Thanks for the info. Did you happen to solve the issue? I can't seem to reproduce this error on colab

**Comment by jsomeara** [comment]
I did what the original person did above, and that fixed it.
