### ISSUE TITLE
Artifacts when converting high resolution cubemap to low resolution equirectangular

### ISSUE THREAD

**Issue by Yukun-Huang** [haruishi43/equilib#24]
Hello! I try to convert a high resolution cubemap (1024x6144x3) to a low resolution equirectangular (e.g., 512x1024x3) using `equilib.cube2equi`, but severe artifacts appeared. Does anyone know how to fix this?

**Cubemap (1024x6144x3) -> Equirectangular (512x1024x3):**
![equi_512](https://github.com/user-attachments/assets/99abe3f8-9f66-4697-8bb7-e0f6704c5605)

**Cubemap (1024x6144x3) -> Equirectangular (2048x4096x3):**
![equi_2048](https://github.com/user-attachments/assets/770a2822-e43b-407a-8279-33617c006546)

**Comment by haruishi43** [comment]
@Yukun-Huang thanks for raising the issue. For the low resolution conversion, what interpolation did you use (I see you tried to use NN #22 )? NN interpolation results in even more artifacts for low resolution conversion (the bilinear interpolation seems to be the best I can do for now... but PRs are always welcome!). If you need a "high-quality" low-resolution equirectangular image, I would recommend just down-sampling the high-resolution equirectangular image you created.

**Comment by Yukun-Huang** [comment]
@haruishi43 Thanks for your great equilib! I am using the default bilinear interpolation. Yes, down-sampling the high-resolution equirectangular image is indeed a feasible solution, but it is not elegant lol.

In fact, I know that these artifacts (moiré pattern) are often encountered when downsampling high-resolution images to low-resolution images. In OpenCV, I can usually use `INTER_AREA` interpolation to get the best moiré-free results. What I really want to ask is, why do panoramic image processing libraries, such as [equilib](https://github.com/haruishi43/equilib) and [py360convert](https://github.com/sunset1995/py360convert), usually only support `nearest` and `bilinear` interpolation? Would it be very difficult to add other interpolation methods like `INTER_AREA`?

**Comment by haruishi43** [comment]
@Yukun-Huang I do support other interpolation in the other transformation (e.g. equi2pers), but they are not tailored to heavy downsampling. As I said in #22, NN interpolation does not work well at all, so bilinear is the best I can do for now. You can override the current grid sampling with others (cv2, scipy, etc...) if you want. Or you can extend the current bilinear sampling by changing the coefficients so that it is close to the cv2's `INTER_AREA` interpolation since `INTER_AREA` seems to be bilinear interpolation with different coefficients.

**Comment by Yukun-Huang** [comment]
@haruishi43 Thanks for your reply! I'll try to see if I can implement something like `INTER_AREA` interpolation to alleviate the artifacts.
