### ISSUE TITLE
Equi2Cube with repeat images

### ISSUE THREAD

**Issue by HHARUP** [haruishi43/equilib#6]
Hi, I'm using Equi2Cube to convert equirectangular images into cubemap but it seems to return it in greyscale with repeated images. Could I ask why that might be and what I can do to solve this? Thank you

**Comment by haruishi43** [comment]
@HHARUP what is the type of image you are using for the input (i.e., channel or single channel and single or batch)?
Also are the cubemaps returned as lists or tuple? The output format can be specified with the arguments (https://github.com/haruishi43/equilib/blob/3cd9be017c0583560821891d764b332318dba032/equilib/equi2cube/base.py#L39).

**Comment by HHARUP** [comment]
Hi, It is a single 3 channel image. I saved the variable for the input array as my image which does the transformation without repeats so it seems to work. I'm not entirely sure why but its done. Thank you for taking a look at this.
