### ISSUE TITLE
enabling gpu in equi2per transform

### ISSUE THREAD

**Issue by zhuqiangLu** [haruishi43/equilib#9]
Hi

THANK YOU for your work and it just saved my life. 

I am wondering how to turn on the gpu support when I transform ERP to perspective image

**Comment by haruishi43** [comment]
Hi @zhuqiangLu , I'm glad my work help you.

If the inputs are `torch.tensor` and they're already on the GPU, it will automatically run in GPU mode.

**Comment by zhuqiangLu** [comment]
Nice to here this, thank you so much
